version: '3.9'

services:
    database:
        image: postgres
        container_name: database_invoices
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=invoices
            - POSTGRES_DB=invoices
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: invoices
        restart: always
        ports:
            - 3333:3333
            - 9229:9229 # pode inserir essa porta tbm pra poder usar o debug
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
